# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 비타민한의원
logo: /assets/logo-default.svg
email: vitagn@vitahani.com
description: >- # this means to ignore newlines until "baseurl:"
  기능의학검사, 소화기클리닉, 수험생클리닉, 통증치료 비타민한의원 홈페이지입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vitahani.com" # the base hostname & protocol for your site, e.g. http://example.com
naver_analytics: s_cdf110f08fa
google_analytics: UA-53073981-14
facebook_pixel: 574121663069933

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
